
export const dataBase = [
    {
        title: "Mieć siano, zjeść siano i zjeść stokrotkę? Oto jest pytanie.",
        author: "Tobiasz Tobiaszewski",
        date: "2020-10-04",
        content: "Quisque eget nulla et augue tincidunt luctus suscipit a ipsum. Proin interdum turpis ac rutrum venenatis. Nam varius orci sem, id semper nisl mattis non.  Donec dapibus est non gravida ultrices. Maecenas eget tincidunt nibh. Sed iaculis vestibulum velit eget ultrices. Duis quis commodo metus. Nunc at mattis libero. Quisque eget augue pulvinar, euismod lectus et, luctus ante. Nunc sit amet tristique mi. Aliquam facilisis gravida nisi et posuere. Aenean dolor nibh, porttitor eu quam in, accumsan maximus lectus. Nulla posuere at felis finibus maximus. Mauris vel nunc quis ipsum tincidunt aliquet. Suspendisse potenti. Suspendisse volutpat diam ac fringilla blandit. Donec faucibus vestibulum mauris in placerat. Nulla consequat, metus sit amet auctor feugiat, purus erat imperdiet leo, hendrerit dignissim leo nisi maximus est. Duis laoreet diam a sem mattis, ac tincidunt mi sodales. Phasellus id euismod elit. Sed orci massa, posuere eget nunc ac, egestas vulputate libero. Etiam elementum id arcu id congue. Maecenas fringilla rutrum massa, eget elementum elit tincidunt porttitor. Aliquam erat volutpat. Quisque hendrerit augue sed felis luctus rutrum. Sed ornare sed arcu commodo facilisis. Aliquam erat volutpat. Nunc mollis neque in nisl interdum scelerisque. Nunc sit amet massa sed orci euismod maximus. Maecenas pharetra lorem ut aliquam varius. Phasellus a massa id augue convallis molestie sagittis quis libero. Mauris iaculis, magna nec bibendum tempor, est velit auctor enim, vitae porta mauris sem ut nibh. Nulla laoreet dolor id mauris condimentum, a consectetur enim ultricies. Ut posuere augue vehicula, auctor eros sit amet, tristique felis. Maecenas vestibulum justo eget rutrum efficitur. Morbi sem magna, ultricies at lorem at, faucibus auctor elit. Phasellus nunc dui, sodales vel libero sed, malesuada venenatis nunc. Proin suscipit, lectus at tempus mollis, risus massa placerat magna, sit amet fermentum mi ex at quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel ligula ut sapien interdum semper. Quisque enim sapien, dapibus ut tristique et, aliquam ac elit.  Proin a pellentesque metus. Duis finibus semper dolor et fringilla. Aenean sit amet feugiat odio, quis facilisis arcu. Sed euismod in erat ut tristique. Quisque efficitur tellus sit amet nunc finibus, ac hendrerit mi hendrerit. Phasellus blandit fermentum volutpat. In hac habitasse platea dictumst. Cras ac nibh sem. ",
        imgSrc: "https://live.staticflickr.com/2920/14132214178_f1e5e94e28_b.jpg",
        alt: "Królik na łące"
    },
    {
        title: "Bobkowe pole minowe",
        author: "Kitek Kitaszewski",
        date: "2021-04-14",
        content: "Nam ultricies placerat urna in rhoncus. Morbi quis commodo odio. Morbi tempus dui libero, quis semper nunc sagittis vitae.  Donec dapibus est non gravida ultrices. Maecenas eget tincidunt nibh. Sed iaculis vestibulum velit eget ultrices. In gravida, nisi ut pharetra viverra, lacus urna scelerisque nibh, nec suscipit turpis massa ac tortor. Mauris in odio aliquet, malesuada libero eget, euismod velit. Donec bibendum est vel urna aliquam aliquet. Nullam accumsan nisl nibh, in sodales magna aliquet sed. Vivamus id sodales massa, eget dignissim urna. Etiam bibendum urna et mauris tempor elementum. Duis fermentum aliquet arcu, id fringilla lorem dignissim id. In ac lorem finibus justo imperdiet rhoncus et id metus. Curabitur quis lacus ac massa sagittis fermentum. Nam viverra ipsum a nisi posuere fermentum. Morbi posuere dolor ac ante interdum, quis congue risus ultrices. Nulla non sollicitudin elit. Aenean congue vestibulum gravida. Ut in lacus sit amet odio tincidunt iaculis in quis tortor. Sed nec dolor id mauris pretium luctus. Cras sagittis consequat orci at faucibus. Suspendisse finibus, ligula quis varius ultricies, justo arcu aliquam erat, eu scelerisque dolor justo vel ante. Duis pretium ex nec velit rutrum, a scelerisque ante iaculis. Donec massa est, posuere a efficitur at, accumsan sed nulla. Nunc sed feugiat neque. Sed sodales at nibh ut hendrerit. Mauris scelerisque porttitor scelerisque. Aenean quam nisi, vulputate sed est tincidunt, congue porttitor massa. Donec feugiat nunc sem. Maecenas fringilla rutrum massa, eget elementum elit tincidunt porttitor. Morbi et aliquam lacus. Vestibulum laoreet iaculis ligula ac lacinia. Cras sit amet metus malesuada, luctus nunc sed, maximus augue. Fusce ac ex in erat auctor dignissim eu eget enim. Aliquam sagittis ultricies metus. Aenean ullamcorper, mauris non aliquet pellentesque, magna nibh hendrerit mauris, sed consequat nisi tortor sed ex. Pellentesque fermentum lacinia justo nec interdum.",
        imgSrc: "https://cdn.britannica.com/98/182098-004-CF9EDEF3.jpg",
        alt: "Królik na łące przy zachodzie słońca"
    },
    {
        title: "Warto czy nie warto? Rozprawka o jedzeniu kabli",
        author: "Tobiasz Tobiaszewski",
        date: "2021-05-23",
        content: "Proin sagittis mattis nulla, vitae pretium ex mollis sit amet. Nam viverra ipsum a nisi posuere fermentum. Morbi posuere dolor ac ante interdum, quis congue risus ultrices. Nulla non sollicitudin elit. Aenean congue vestibulum gravida. Ut in lacus sit amet odio tincidunt iaculis in quis tortor. Sed nec dolor id mauris pretium luctus. Cras sagittis consequat orci at faucibus. Suspendisse finibus, ligula quis varius ultricies, justo arcu aliquam erat, eu scelerisque dolor justo vel ante. Duis pretium ex nec velit rutrum, a scelerisque ante iaculis. Donec massa est, posuere a efficitur at, accumsan sed nulla. Nunc sed feugiat neque. Suspendisse volutpat diam ac fringilla blandit. Donec faucibus vestibulum mauris in placerat. Sed sodales at nibh ut hendrerit. Phasellus tellus lorem, suscipit vel sapien dignissim, feugiat porttitor arcu. Etiam bibendum urna et mauris tempor elementum. Duis fermentum aliquet arcu, id fringilla lorem dignissim id. In ac lorem finibus justo imperdiet rhoncus et id metus. Curabitur quis lacus ac massa sagittis fermentum. Mauris scelerisque porttitor scelerisque. Aenean quam nisi, vulputate sed est tincidunt, congue porttitor massa. Donec feugiat nunc sem. Morbi et aliquam lacus. Vestibulum laoreet iaculis ligula ac lacinia. Cras sit amet metus malesuada, luctus nunc sed, maximus augue. Donec dapibus est non gravida ultrices. Maecenas eget tincidunt nibh. Sed iaculis vestibulum velit eget ultrices. Donec facilisis sollicitudin diam sit amet ullamcorper. Nam a leo in purus gravida pharetra. Pellentesque dignissim ultricies ligula, sit amet semper metus vehicula ut. Pellentesque ut mi urna. Maecenas fringilla rutrum massa, eget elementum elit tincidunt porttitor. Vestibulum viverra, lectus dictum condimentum pulvinar, risus ligula pretium lacus, in pulvinar velit mauris id purus.",
        imgSrc: "https://myhouserabbit.com/wp-content/uploads/2014/05/coco2.jpg",
        alt: "Królik jedzący natkę pietruszki"
    }
]